# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-CrowdAuth
version:      1.3
version_from: lib/Apache/CrowdAuth.pm
installdirs:  site
requires:
    Atlassian::Crowd:              1
    Cache::Cache:                  1.05
    Digest::SHA1:                  0
    Error:                         0
    SOAP::Lite:                    0.69

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
