# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Atlassian-Crowd
version:      1.3
version_from: lib/Atlassian/Crowd.pm
installdirs:  site
requires:
    Error:                         0.1
    SOAP::Lite:                    0.69
    version:                       0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
